env: dev
log_level: debug
http_srv:
  address: :8800
  keep_alive: true
  read_timeout: 30s
  write_timeout: 30s
aliyun:
  access_key_id: ${ALIYUN_ACCESS_KEY_ID}
  access_key_secret: ${ALIYUN_ACCESS_KEY_SECRET}
  region_id: cn-shenzhen